FROM maven:3.8.7-openjdk-18-slim

LABEL maintainer="Konstantin"
LABEL description="JiraRush application"
LABEL version="1.0"
LABEL profile="dev (for run full app with h2)"
LABEL build="docker build -t jira-dev-img -f Dockerfile-dev ."
LABEL run="docker run -p 8080:8080 --name jira-dev jira-dev-img:latest"

WORKDIR /app
COPY pom.xml .
COPY src ./src
COPY resources ./resources
COPY lombok.config ./lombok.config
RUN mvn clean package -DskipTests
RUN mv ./target/*.jar ./app.jar
RUN rm -rf ./target
RUN rm -rf ./src
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "cd /app && java -jar /app/app.jar --spring.profiles.active=dev"]