spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://jirarush-db:5432/jira}
    username: ${DATASOURCE_USERNAME:jira}
    password: ${DATASOURCE_PASSWORD:JiraRush}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID:3d0d8738e65881fff266}
            client-secret: ${OAUTH2_GITHUB_SECRET:0f97031ce6178b7dfb67a6af587f37e222a16120}
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID:329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com}
            client-secret: ${OAUTH2_GOOGLE_SECRET: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}
          gitlab:
            client-id: ${OAUTH2_GITLAB_CLIENT_ID:b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494}
            client-secret: ${OAUTH2_GITLAB_SECRET:e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004}

  mail:
    username: ${MAIL_USERNAME:jira4jr@gmail.com}
    password: ${MAIL_PASSWORD:zdfzsrqvgimldzyj}
    port: ${MAIL_PORT:587}